INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 1', 'P1 Description', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 2', 'P2 Description', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 3', 'P3 Description', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 4', 'P4 Description', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 5', 'P5 Description', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 6', 'P6 Description', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 7', 'P7 Description', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 8', 'P8 Description', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 9', 'P9 Description', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 10', 'P10 Description', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 11', 'P11 Description', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 12', 'P12 Description', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 13', 'P13 Description', 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Product 14', 'P14 Description', 20);


INSERT INTO NEWS (TITLE, DESCRIPTION) VALUES ('News Title 1', 'News Description 1');
INSERT INTO NEWS (TITLE, DESCRIPTION) VALUES ('News Title 2', 'News Description 2');
INSERT INTO NEWS (TITLE, DESCRIPTION) VALUES ('News Title 3', 'News Description 4');
INSERT INTO NEWS (TITLE, DESCRIPTION) VALUES ('News Title 5', 'News Description 5');
INSERT INTO NEWS (TITLE, DESCRIPTION) VALUES ('News Title 6', 'News Description 6');
INSERT INTO NEWS (TITLE, DESCRIPTION) VALUES ('News Title 7', 'News Description 8');
INSERT INTO NEWS (TITLE, DESCRIPTION) VALUES ('News Title 9', 'News Description 9');
INSERT INTO NEWS (TITLE, DESCRIPTION) VALUES ('News Title 10', 'News Description 10');
INSERT INTO NEWS (TITLE, DESCRIPTION) VALUES ('News Title 11', 'News Description 11');
INSERT INTO NEWS (TITLE, DESCRIPTION) VALUES ('News Title 12', 'News Description 12');
INSERT INTO NEWS (TITLE, DESCRIPTION) VALUES ('News Title 13', 'News Description 13');
INSERT INTO NEWS (TITLE, DESCRIPTION) VALUES ('News Title 14', 'News Description 14');