CREATE TABLE PRODUCT(
  PRODUCT_ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL UNIQUE,
  DESCRIPTION  CHAR(50) NOT NULL,
  PRICE NUMBER(6) NOT NULL
);

CREATE TABLE NEWS(
  NEWS_ID BIGSERIAL PRIMARY KEY,
  TITLE VARCHAR(50) UNIQUE,
  DESCRIPTION VARCHAR(200)
);